### ISSUE TITLE
Make request cancellable

### ISSUE THREAD

**Issue by fabianfett** [soto-project/soto-core#172]
Use the same interface that AysncHTTPClient uses:

```swift
protocol HTTPClient {
  func execute(request: AWSHTTPRequest, timeout: TimeAmount) -> AWSTask< AWSHTTPResponse >
}

class AWSTask<Response: AWSHTTPResponse > {
  let response: EventLoopFuture<Response>
  let eventLoop: EventLoop { get }

  func cancel()
}
```

**Comment by fabianfett** [comment]
Yes! If a web request is dropped (in a server use-case), there should be ways to stop the work done (whatever it is).

**Comment by adam-fowler** [comment]
What does cancel actually mean? Can we cancel a request once it has been sent.

**Comment by fabianfett** [comment]
Well the same it means to cancel an HTTP Request. Just drop the connection.
