### ISSUE TITLE
Move over SwiftNIO allocation integration tests

### ISSUE THREAD

**Issue by fabianfett** [soto-project/soto-core#265]
We should verify be able to verify that we don't increase the number of needed allocations per request in AWSClient.

This should be made part of the CI.

An example how this can be achieved can be seen here:

https://github.com/fabianfett/pure-swift-json/tree/master/IntegrationTests/tests_04_performance
https://github.com/fabianfett/swift-base64-kit/tree/master/IntegrationTests

We probably need a setup in which we run the request against something. LocalStack? Create our own MockServer?

@adam-fowler what are your thoughts?

**Comment by adam-fowler** [comment]
A mock server should do the trick.

**Comment by fabianfett** [comment]
Depends on: https://github.com/swift-aws/aws-sdk-swift-core/issues/267

**Comment by adam-fowler** [comment]
I had a look into this and found starting up each integration test took so long as it had to download all the dependencies. Need to find a better way to do this.
