### ISSUE TITLE
Revisit Public API before 5.0.0 release

### ISSUE THREAD

**Issue by fabianfett** [soto-project/soto-core#290]
Before we release 5.0.0 we should revisit our API to make sure we expose really only what is needed to our endusers. This should make SemVer more easy.

Also we should probably add something that detects public API changes. I know there is something NIO uses... We should probably look into that...

**Comment by adam-fowler** [comment]
You can find the public API here https://soto-project.github.io/soto-core/5.x.x/index.html
I've had a look through it and everything that is public is there for a reason.
