### ISSUE TITLE
AWSSwiftSDKCore can not locate config file in sandboxed environments 

### ISSUE THREAD

**Issue by sebsto** [soto-project/soto-core#359]
**Describe the bug**
When using ConfigFileCredentialProvider on MacOS in a Sandboxed app, the path `~/.aws/credentials` is expanded to `/Users/name/Library/Containers/bundle-id/Data/.aws/credentials`

The `NSString.expandingTildeInPath` here 
https://github.com/swift-aws/aws-sdk-swift-core/blob/main/Sources/AWSSDKSwiftCore/Credential/ConfigFileCredentialProvider.swift#L137
must be replaced with posix code such as 

```swift 
    let pw = getpwuid(getuid())
    let home = pw?.pointee.pw_dir
```

**To Reproduce**
Create a sandboxed app, initialize the AWS SDK with 

```swift 
        self.awsClient = AWSClient(credentialProvider: .configFile(), middlewares: [AWSLoggingMiddleware()], httpClientProvider: .createNew)
        self.s3 = S3(client: awsClient)
```

The code produce the error message `No credential provider found` at line https://github.com/swift-aws/aws-sdk-swift-core/blob/main/Sources/AWSSDKSwiftCore/Credential/DeferredCredentialProvider.swift#L49

**Expected behavior**
credentials file should be loaded

**Setup (please complete the following information):**
 - OS: [e.g. iOS] Mac OS 10.15
 - Version of aws-sdk-swift [e.g. 3.0] 5.x.x branch
 - Authentication mechanism [hard-coded credentials, IAM Instance Profile on EC2, etc]  ConfigFile

**Additional context**

**Comment by adam-fowler** [comment]
@sebsto have you verified this code. Surely a sandboxed app would not have access to the ~/.aws/credential file.

**Comment by sebsto** [comment]
Yes, it works, providing the app has the correct entitlements.  Reading on ~/.aws requires explicit user selection (through a `NSOpenPanel()`) I also tested `~/Downloads`

I am sending a PR which is harmless for non sandboxed environments and solves this for sandboxed environments
