### ISSUE TITLE
extend HTTPClientProvider with createNew on provided EventLoopGroup

### ISSUE THREAD

**Issue by pokryfka** [soto-project/soto-core#382]
**Is your feature request related to a problem? Please describe.**

In my (limited) experience with AWSSDKSwift/Soto I find that typically I want to share the event loop but dont
really need/care about the HTTP client implementation as such. (And would rather not need to manage its lifecycle.)

**Describe the solution you'd like**

It would be convenient to make `AWSClient` create new HTTP client on provided `EventLoopGroup`
and have it manage the HTTP client lifecycle.

```swift
AWSClient(httpClientProvider: .createNewOnSharedEventLoopGroup(eventLoopGroup))
```

(not sure about the naming)

**Describe alternatives you've considered**

Its possible to create a HTTP client and provide it to the AWS client.
This requires creating/importing HTTP client and managing its lifcycle.

**Comment by adam-fowler** [comment]
Ok sounds fine. Maybe call it `.createNewUsingEventLoopGroup`.
