### ISSUE TITLE
Add support for `AWS_WEB_IDENTITY_TOKEN_FILE` credential provider

### ISSUE THREAD

**Issue by t089** [soto-project/soto-core#391]
**Is your feature request related to a problem? Please describe.**
With IAM roles for service accounts on Amazon EKS clusters, you can associate an IAM role with a Kubernetes service account. This service account can then provide AWS permissions to the containers in any pod that uses that service account. With this feature, you no longer need to provide extended permissions to the Amazon EKS node IAM role so that pods on that node can call AWS APIs. [1]

**Describe the solution you'd like**
Create a new credentials provider that is part of the default credentials provider chain, that uses the environment variables `AWS_WEB_IDENTITY_TOKEN_FILE`, `AWS_ROLE_ARN`, and `AWS_ROLE_SESSION_NAME` to obtain AWS credentials by using the `STS.AssumeRoleWithWebIdentityCredentialProvider` to exchange the OIDC token in `AWS_WEB_IDENTITY_TOKEN_FILE` for valid AWS credentials.

Java implementation is here:
[WebIdentityTokenFileCredentialsProvider.java](https://github.com/aws/aws-sdk-java-v2/blob/master/core/auth/src/main/java/software/amazon/awssdk/auth/credentials/WebIdentityTokenFileCredentialsProvider.java)

**Additional context**
What is a bit tricky: the default credentials provider chain is defined in soto/soto-core, but STS is in soto/soto ... Somehow this circular dependency needs to be resolved.

[1]: https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html

**Comment by adam-fowler** [comment]
Something like this https://github.com/soto-project/soto/blob/968977cf2be8ca19da525bd9d57ffbd1b8473045/Sources/Soto/Extensions/STS/STS%2BCredentialProvider.swift#L112

**Comment by t089** [comment]
Yes exactly, I mentioned this guy in the issue description ;) The pieces are all there, they just need to be connected. I am happy do it, but I am not sure about how to have this in `soto-core` because it requires access to `STS`.

**Comment by adam-fowler** [comment]
You can't see how you'd make it part of the default chain because of the issues you have already mentioned with circular dependencies. But given you can do the following already

```
let request = STS.AssumeRoleWithWebIdentityRequest(roleArn: myRoleArn, roleSessionName: mySessionName, webIdentityToken: myWebToken)
let client = AWSClient(credentialProvider: .stsWebIdentity(request, region: .euwest1))
```
 
Creating a new version of this which uses the environment variables mentioned above and loads the web identity token from a file shouldnt be too hard. I'd be happy for you to give it a go.

**Comment by adam-fowler** [comment]
@t089 Do you want to try https://github.com/soto-project/soto/pull/451

```swift
let client = AWSClient(credentialProvider: .stsWebIdentityTokenFile(region: .useast1), ...)
```
I haven't got an EKS setup so haven't been able to test this.

**Comment by t089** [comment]
Ah nice, thanks for taking this up. Will give it a spin after Christmas!

**Comment by adam-fowler** [comment]
https://github.com/soto-project/soto/pull/451
