### ISSUE TITLE
Add support for IAM roles in shared credentials file

### ISSUE THREAD

**Issue by eneko** [soto-project/soto-core#405]
**Is your feature request related to a problem? Please describe.**
Add support for IAM role when loading credentials from file (see `role_arn` and `source_profile` under [Supported config file settings](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html#cli-configure-files-settings).

- [Using an IAM role in the AWS CLI](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-role.html)
- [AWS Secure Token Service - AssumeRole](https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRole.html)
- [Boto3 - Assume Role Provider](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/credentials.html#assume-role-provider)

**Describe the solution you'd like**
Ideally, Soto would automatically handle retrieval and caching of temporary credentials for IAM roles, similar to how Boto3 does.

**Describe alternatives you've considered**
Looking at [this response in a similar feature request](https://github.com/soto-project/soto-core/issues/391), it seems that `stsAssumeRole` credentials provider could be used. However, I cannot find anywhere in the code where `role_arn` and `source_profile` are loaded from `~/.aws/credentials` file, nor any references where `~/.aws/config` is loaded.

**Additional context**
The following are examples of shared configuration files where an IAM role profile is configured. This profile `foo` uses credentials from `default` profile (as referenced by `source_profile` to retrieve temporary credentials that will be used to access AWS resources.

Example `~/.aws/config` file:
```
cat ~/.aws/config
[profile default]
region = us-west-2

[profile foo]
region = us-west-2
role_session_name = foo_user@example.com
```

Example `~/.aws/credentials` file:
```
[default]
aws_account_id           = fooaccount
aws_access_key_id        = FOOKEYID
aws_secret_access_key    = FOOSECRETKEY
aws_session_token        = IQoJb3JEXAMPLE=
aws_security_token       = IQoJb3JEXAMPLE=
x_principal_arn          = arn:aws:sts::...
x_security_token_expires = 2020-11-14T09:11:17-08:00

[foo]
role_arn              = arn:aws:iam::...
source_profile        = default
```

Additional example configuration files are available in [AWS documentation](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-role.html) and [Boto3 documentation](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/credentials.html#assume-role-provider).

**Comment by adam-fowler** [comment]
There is a slight issues with implementing this as it generates a circular dependency where SotoCore is dependent on SotoSTS which is dependent on SotoCore.

**Comment by eneko** [comment]
To solve that, we can consider these options:

- Option A: Have SotoCore do this service request once, without using SotoSTS, and cache the response credentials.
- Option B: Implement this feature in SotoSTS. 

I would prefer Option A, since all the logic for loading configuration files is already present in SotoCore. While it will require manually implementing a client for consuming the STS endpoint, the implementation details can be hidden and not exposed to consumers of the library.

In both cases, we would want to update the logic to load and process shared configuration files (both `~/.aws/credentials` and `~/.aws/config`, with overridable paths), looking for `role_arn`, `source_profile` and other configuration settings needed.

Option B would require the logic in SotoCore for loading credentials from file to be exposed, somehow, so SotoSTS can process the settings accordingly. Choosing this option would also mean SotoSTS would be required for processing shared configuration files, which might not be ideal.

**Comment by adam-fowler** [comment]
I'm not a great fan of A but is better than B. I can bring across the credential provider for assume role. Hopefully it won't drag across too much code. 

One thing we won't know is what region to run the STS assume role call. We'll just have to use useast1 which is what all the IAM code is run from. 

There are two other sections to the code. 
1) the extra parsing of the credential config file
2) running an additional credential provider when we have all the details from the config file. 

Given we will have all this we might as well support the "credential_source" tag as well.

**Comment by adam-fowler** [comment]
@eneko do you think you can do the file parsing?

**Comment by eneko** [comment]
I'd be happy to give it a try, probably later this week.

**Comment by adam-fowler** [comment]
#406 thats the STS AssumeRole credential provider

**Comment by adam-fowler** [comment]
@eneko I have also change the ConfigFileCredentialProvider to have an internal Credential Provider. All you need to do is return the correct credential provider from `getSharedCredentialsFromDisk`.

**Comment by eneko** [comment]
Draft PR #408 is in progress
