### ISSUE TITLE
generateOutputShape throws when x-amz-executed-version is not $LATEST

### ISSUE THREAD

**Issue by saltzmanjoelh** [soto-project/soto-core#429]
**Describe the bug**
Lambdas can be versioned. These versions are ints that are automatically incremented by 1 in the AWS Console. When executing a version that is not $LATEST generateOutputShape will throw an error about a type mismatch. 

**To Reproduce**
1. Create a Lambda function (called mytest)
2. Publish a version (1)
3. Update the code
4. Publish another version (2)
5. Create an alias (called myalias) and point it to version 1
6. Invoke the Lambda `Lambda.FunctionConfiguration.init(functionName: "mytest:myalias")

**Expected behavior**
An InvocationResponse should be received.

**Setup (please complete the following information):**
 - OS: macOS
 - Version of aws-sdk-swift: main branch 55c94c4
 - Authentication mechanism: local credentials file

**Additional context**
Given the key and value from the headers:
    - key : "x-amz-executed-version"
    - value : "1"
Around line 172 of AWSResponse.swift.
The value ("1") is converted to stringValue. Later down the code, we try to get the Double(stringValue), which works since it's "1". Finally, when `try decoder.unbox(dictionary, as: type)` is called, an error is thrown.

`throw DecodingError._typeMismatch(at: self.codingPath, expectation: type, reality: value)`
codingPath == CodingKeys(stringValue: "X-Amz-Executed-Version", intValue: nil)
type == String
value == 1 (not a string)

```swift 
        // add header values to output dictionary, so they can be decoded into the response object
        for (key, value) in self.headers {
            let headerParams = Output.headerParams
            if let index = headerParams.firstIndex(where: { $0.key.lowercased() == key.lowercased() }) {
                // check we can convert to a String. If not just put value straight into output dictionary
                guard let stringValue = value as? String else {
                    outputDict[headerParams[index].key] = value
                    continue
                }
                if let number = Double(stringValue) { // Problem is here when stringValue == "1"
                    outputDict[headerParams[index].key] = number.truncatingRemainder(dividingBy: 1) == 0 ? Int(number) : number
                } else if let boolean = Bool(stringValue) {
                    outputDict[headerParams[index].key] = boolean
                } else {
                    outputDict[headerParams[index].key] = stringValue
                }
            }
        }
```

*** Example Test ***

```swift
func testHeaderResponseDecodingStringWithIntegerValue() {
        struct Output: AWSDecodableShape {
            static let _encoding = [AWSMemberEncoding(label: "h", location: .header(locationName: "header-member"))]
            let h: String
            private enum CodingKeys: String, CodingKey {
                case h = "header-member"
            }
        }
        let response = AWSHTTPResponseImpl(
            status: .ok,
            headers: ["header-member": "1"],
            bodyData: nil
        )

        // XML
        var awsXMLResponse: AWSResponse?
        var xmlResult: Output?
        XCTAssertNoThrow(awsXMLResponse = try AWSResponse(from: response, serviceProtocol: .query, raw: false))
        XCTAssertNoThrow(xmlResult = try awsXMLResponse?.generateOutputShape(operation: "Test"))
        XCTAssertEqual(xmlResult?.h, "1")

        // JSON
        var awsJSONResponse: AWSResponse?
        var jsonResult: Output?
        XCTAssertNoThrow(awsJSONResponse = try AWSResponse(from: response, serviceProtocol: .restjson, raw: false))
        XCTAssertNoThrow(jsonResult = try awsJSONResponse?.generateOutputShape(operation: "Test"))
        XCTAssertEqual(jsonResult?.h, "1")
    }
```

`XCTAssertNoThrow failed: threw error "typeMismatch(Swift.String, Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "header-member", intValue: nil)], debugDescription: "Expected to decode String but found a number instead.", underlyingError: nil))"`

Here is the pattern from the docs.
Pattern: (\$LATEST|[0-9]+)
https://docs.aws.amazon.com/lambda/latest/dg/API_Invoke.html#SSS-Invoke-response-ExecutedVersion

**Comment by adam-fowler** [comment]
@saltzmanjoelh Ouch, that's not easy to fix. The dictionary decoder is based off the JSON decoder in Foundation which is fussy about whether its input is a string or a number. If Soto finds a header which can be parsed as a number it provides it to the dictionary decoder as a number. Not exactly correct I know

I'm gonna need to either make the dictionary decoder less fussy or find a better way to work out what type is required.

**Comment by saltzmanjoelh** [comment]
Wow that was fast and the fix is super clean. Thanks! Is there anything else that I can help with on this one?

**Comment by adam-fowler** [comment]
https://github.com/soto-project/soto-core/releases/tag/5.2.2
