### ISSUE TITLE
JMESPath dependency

### ISSUE THREAD

**Issue by mxcl** [soto-project/soto-core#451]
I noticed a new dependency in my stack, so hunted and found it here.

I can't find rationale for why it exists now. I don’t like new dependencies in my stack.

Looking through what it effects it seems like it should really be a separate module.

Opened for discussion. Thanks.

**Comment by adam-fowler** [comment]
The JMESPath dependency is required to support the new waiter feature. This is a feature that is standard in all the official SDKs so I felt it was something we should support. JMESPath is used to indicate a field or group of fields in a response from AWS. The AWS models for the waiters use JMESPath extensively.

I should have been clearer in the release notes that the new release brought in a new dependency, sorry.

**Comment by mxcl** [comment]
Thanks for the update 👍🏻

Many of us sincerely appreciate this package and the work you do.

Whole module optimization should remove it from my final binary if unused, and if you think it is standard then it makes sense to have it in the main package. Still a shame I'm compiling stuff I don't need time and again, but you have thought it through.
