### ISSUE TITLE
Build fails w/ `tls_protocol_version_t` error caused by AsyncHTTPClient

### ISSUE THREAD

**Issue by guillaumekh** [soto-project/soto-core#486]
**Describe the bug**
Xcode project fails to build with following error:
```
AsyncHTTPClient/NIOTransportServices/TLSConfiguration.swift:25:35: 
'tls_protocol_version_t' is only available in macOS 10.15 or newer
```

**To Reproduce**
1. add soto@5.11.0 to a macOS app Xcode project 
2. build

**Expected behavior**
Xcode project should build.

**Setup (please complete the following information):**
 - OS: macOS 11.6.2
 - Xcode: 13.2.1
 - soto: 5.11.0

**Additional context**
This error is caused by AsyncHTTPClient. It was fixed in version 1.5.1. `soto-core` currently uses 1.4.0. See:
- https://github.com/swift-server/async-http-client/issues/532
- https://github.com/swift-server/async-http-client/pull/411

I see this is already fixed on soto-core's `main` branch, which has upgraded the dependency to 1.6.4, but maybe there's value in keeping this issue open until `soto-core` & `soto` releases are made which ship the fix?

**Comment by adam-fowler** [comment]
Fixed
