### ISSUE TITLE
Extra spaces in the Authorisation header do not match Amazon's examples

### ISSUE THREAD

**Issue by mildm8nnered** [soto-project/soto-core#521]
**Describe the bug**

At https://github.com/soto-project/soto-core/blob/f8a8db612a6bca7a05f69e975464f7a841f43617/Sources/SotoSignerV4/signer.swift#L224

```
        let authorization = "AWS4-HMAC-SHA256 " +
            "Credential=\(credentials.accessKeyId)/\(signingData.date)/\(region)/\(name)/aws4_request, " +
            "SignedHeaders=\(signingData.signedHeaders), " +
            "Signature=\(signature)"
```

explicit spaces are added to the end of the `Credential` and `SignedHeaders` fields, which does not match the examples that Amazon provides at https://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-header-based-auth.html

For example:

`AWS4-HMAC-SHA256 Credential=AKIAIOSFODNN7EXAMPLE/20130524/us-east-1/s3/aws4_request,SignedHeaders=host;x-amz-content-sha256;x-amz-date,Signature=fea454ca298b7da1c68078a5d1bdbfbbe0d65c699e0f91ac7a200a0136783543`

Obviously this does not seem to cause a problem, but is there any reason for those extra spaces?

Context - I'm replacing my own hand-rolled signer with yours, and then my unit tests, which are based on Amazon's samples,started failing.

**To Reproduce**

N/A

**Expected behavior**

N/A

**Setup (please complete the following information):**

N/A

**Additional context**

N/A

**Comment by adam-fowler** [comment]
I hadn't noticed them before. I can add them in if it doesn't break anything. Which samples are you using for your tests? Sounds like a good idea to add to my tests.

**Comment by adam-fowler** [comment]
Sorry I see you added the link in your issue.

**Comment by adam-fowler** [comment]
#522
